apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "hydra") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "hydra") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  self_hosted.yaml: |
    server_url: https://hydra.devzero.dev
    
    listen_addr: 0.0.0.0:8443
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 127.0.0.1:50443
    grpc_allow_insecure: false
    
    prefixes:
      v6: fd7a:115c:a1e0::/48
      v4: 100.64.0.0/10
    
    derp:
      server:
        enabled: false
        region_id: 999
        region_code: "headscale"
        region_name: "Headscale Embedded DERP"
        stun_listen_addr: "0.0.0.0:3478"
    
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
    
    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m
    node_update_check_interval: 10s
    
    database:
      type: postgres
      postgres:
        host: hydra-db-postgresql.devzero.svc.cluster.local
        port: 5432
        name: hydra
        user: hydra
    
    log:
      format: text
      level: debug
    
    acl_policy_path: /etc/headscale/acl.json
    
    dns_config:
     override_local_dns: false
     nameservers:
       - 1.1.1.1
       - 1.0.0.1
     domains: []
     magic_dns: true
     base_domain: dv0.io
    
    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"
    
    #oidc:
    #  only_start_if_oidc_is_available: true
    #  issuer: "https://devinfra.us.auth0.com/"
    #  client_id: "kMRz7j6xY3LtBioPDpns14TBCwr2EVX7"
    #  strip_email_domain: true
    #  allowed_domains:
    #    - devzero.dev
    
    logtail:
      enabled: false
    
    randomize_client_port: false
    
    otel_host: datadog.datadog.svc.cluster.local
    otel_port: 4317
    environment: "preproduction"
