apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "logsrv") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "logsrv") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  self_hosted.yaml: |
    service_port: {{ .Values.logsrv.service.port }}
    health_probe_port: 9999
    log_level: debug
    
    postgres_url: "" # from envvar
    pgpassword: "" # from envvar
    queue_url: "" # form envvar
    num_consumers: 20
    
    self_hosted: false
    
    allowed_cors_origins:
    - http://localhost:3000
    
    auth0_domains:
    - auth.devzero.example
    auth0_audience:
    - https://devzero.example/api
    refresh_jwks_timer: 3600
    vaulted_auth_public_key: {{ .Values.auth.public_key | quote }}
