apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "web") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "web") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  self_hosted.yaml: |
