apiVersion: v2
name: dz-control-plane
description: DevZero Self Hosted Control Plane
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://docs.devzero.io/docs/self-hosted
icon: https://avatars.githubusercontent.com/u/71745520?s=400&u=10cb3d6fb9e509873fc2591ca11220573399a5de&v=4 # TODO: maybe host this image in devzero.io/static/...
dependencies:
  - name: vault
    version: 0.28.1
    repository: https://helm.releases.hashicorp.com
  - name: minio
    version: 5.2.0
    repository: https://charts.min.io/
    condition: minio.enabled
  # TODO: helm chart for sqs drop-in replacement (or allow logsrv to use kafka)
  - name: mysql
    version: 11.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: mongodb
    version: 16.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.0.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: artifactory
    version: 107.90.15
    repository: https://charts.jfrog.io
    condition: artifactory.enabled