apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "pulse") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "pulse") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  self_hosted.yaml: |
    server_grpc_host: 0.0.0.0
    server_grpc_port: {{ .Values.pulse.service.port }}
    environment: production 
    metrics_address: 0.0.0.0:{{ .Values.pulse.service.metricsPort }}
    sentry_debug: false
    use_timescale: true
    postgres_password: 
    postgres_user: 
    postgres_host: 
    postgres_port: 
    postgres_database:  
    postgres_ssl: 
    mysql_user:  
    mysql_password: 
    mysql_host: 
    mysql_port: 
    mysql_database: pulse 
    dev_lake_encryption_secret: 
    open_api_token: 
