name: "[CRDS] Chart Update"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  id-token: write
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-tags: true
          fetch-depth: 0
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.15.4' # default is latest (stable)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::056855531191:role/github-actions-oidc-role
          aws-region: us-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Login to ECR and helm
        run: aws ecr-public get-login-password --region "us-east-1" | helm registry login --username AWS --password-stdin public.ecr.aws/v1i4e1r2
      - name: Build dependencies
        run: helm dependency build ./dz-crds
      - name: Update chart
        run: helm package ./dz-crds
      - name: Push chart
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          helm push dz-crds-${VERSION}.tgz oci://public.ecr.aws/v1i4e1r2/charts
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-tags: true
          fetch-depth: 0
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.15.4' # default is latest (stable)
      - name: Lint devbox chart
        run: helm lint ./dz-crds